version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=librarydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always